---
version: '3'
services:
  postgresql:
    image: postgres:11.3
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    volumes:
    - postgresql_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/exchange-six
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
volumes:
  postgresql_data: 
